name: Test API

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Install all production dependencies first
        pip install --no-cache-dir -r requirements.txt
        # Install test dependencies
        pip install --no-cache-dir pytest pytest-cov pytest-asyncio httpx
        
    - name: Run tests
      run: |
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest tests/ --cov=app --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml